Adding latest datamover config changes
OpenMPDK/dss-ansible pull request #14
Opened 2023-03-31 00:20 UTC by nsarras

2023-03-31 23:40 UTC, velomatt requested changes
Please review inline comments

2023-03-31 23:40 UTC, velomatt commented on group_vars/all.yml
> +# datamover_compaction: yes
This var is already set: https://github.com/OpenMPDK/dss-ansible/blob/aece12f7f5b3f5f0fc1fe65e583494c31e7b9f59/group_vars/all.yml#L150

This is also adding another flavor of "yaml truthiness" but `yes` essentially has the same value as `true` in this case.

2023-03-31 23:40 UTC, velomatt commented on roles/create_datamover_conf/defaults/main.yml
> +datamover_compaction: yes
Same as above comment

2023-03-31 23:40 UTC, velomatt commented on roles/create_datamover_conf/templates/config.json.j2
> +  "compaction": "{{ datamover_compaction }}"
If `datamover_compaction` is `yes`, then the template will set this value to `true`.

see: https://zzz.buzz/notes/ansible-truth-table/

If we want it to print the string `yes` - we will need to do so explicitly. But if we set `datamover_compaction` to a string, then we can't use it to evaluate as a boolean in Ansible any more.

2023-03-31 23:44 UTC, nsarras commented on roles/create_datamover_conf/templates/config.json.j2
> +  "compaction": "{{ datamover_compaction }}"
ok, then I think we want to explicitly list "yes" as that is the underlying input that the DataMover code expects

2023-04-03 23:36 UTC, velomatt approved these changes
I have tested this and it works. Approved

2023-04-03 23:37 UTC, merged